# Generated by Django 2.2.9 on 2019-12-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='note',
            new_name='notes',
        ),
    ]
