# Generated by Django 2.2.9 on 2019-12-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_auto_20191223_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='text',
        ),
    ]
